src/vogar/android/AndroidSdk.java: fix "--mode activity", at least from the root of a build tree. Tests that require a Context still fail, but this is a step forward:
    junit.framework.AssertionFailedError: Context is null. setContext should be called before tests are run
    	at junit.framework.Assert.assertNotNull(Assert.java:218)
    	at android.test.AndroidTestCase.testAndroidTestCaseSetupProperly(AndroidTestCase.java:46)